### ISSUE TITLE
MVC application structure

### ISSUE THREAD

**Issue by jakconstantin** [KiberneticWorm/json_placeholder_app#1]
Доброе время суток. Есть вопрос касательно Вашего примера работы с MVC Flutter. Вопрос такой - как правильно организовать получение данных по порционному запросу, то если запрашивать данные кусочками по 10, например, элементов. Сейчас делается один запрос для получения сразу всей информации и ожидается когда это закончится и получаем final posts = (state as PostResultSuccess).postList.posts;  в какую сторону смотреть, что б заставить controller еще раз запросить запрос?
Заранее спасибо за помощь)))

---
Good time of the day. I have a question regarding your example of working with MVC from flutter. The question is - how to properly organize the receipt of data on a batch request, then if you request data in pieces of 10, for example, elements. Now one request is made to get all the information at once and it is expected when it ends and we get final posts = (state as PostResultSuccess).postList.posts; in which direction to look, what would make the controller request the request again?
Thanks in advance for your help)))

**Comment by KiberneticWorm** [comment]
В целом никаких проблем нет, можно в контроллере хранить ключ по которому вы будете получать отдельную порцию из 10 элементов. При каждом новом запросе значение ключа будет увеличиваться.  А чтобы отследить последний элемент  юзайте ScrollController.

**Comment by jakconstantin** [comment]
Спасибо большое за ответ. Я начал использовать ScrollController, но пока не получается определить в каком случае вызвать получение новых данных и каким образом заставить Widget _buildContent() перезапуститься, чтоб получить новые данные и отобразить их. Может у Вас есть пример такой работы?

**Comment by KiberneticWorm** [comment]
Посмотрите на StackOverflow
https://stackoverflow.com/questions/56071731/scrollcontroller-how-can-i-detect-scroll-start-stop-and-scrolling
